/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Postcard } from '../../models/postcard';

export interface ViewCard$Params {
  cardId: string;
}

export function viewCard(http: HttpClient, rootUrl: string, params: ViewCard$Params, context?: HttpContext): Observable<StrictHttpResponse<Postcard>> {
  const rb = new RequestBuilder(rootUrl, viewCard.PATH, 'get');
  if (params) {
    rb.query('cardId', params.cardId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Postcard>;
    })
  );
}

viewCard.PATH = '/postcard/view';
