/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AliasesCountData } from '../models/aliases-count-data';
import { BaseResponse } from '../models/base-response';
export type AliasesCountResponse = {
'data'?: AliasesCountData;
} & BaseResponse;
