/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AliasData } from '../models/alias-data';
import { BaseResponse } from '../models/base-response';
export type AliasResponse = {
'data'?: AliasData;
} & BaseResponse;
