/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AliasData {

  /**
   * Alias name
   */
  alias?: string;

  /**
   * Analytics settings
   */
  analytics?: Array<{
'enabled'?: boolean;
'public'?: boolean;
}>;

  /**
   * Is TinyURL archived?
   */
  archived?: boolean;

  /**
   * Alias createion datetime
   */
  created_at?: string;

  /**
   * Is TinyURL deleted?
   */
  deleted?: boolean;

  /**
   * Target domain
   */
  domain?: string;

  /**
   * Alias expiration datetime
   */
  expires_at?: string | null;

  /**
   * Tags
   */
  tags?: Array<string>;

  /**
   * Short URL
   */
  tiny_url?: string;
}
