/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BaseResponse {

  /**
   * Operation result code. Possible codes:
   *                 <ul>
   *                   <li><b>0</b> - OK</li>
   *                   <li><b>1</b> - Not authorized</li>
   *                   <li><b>2</b> - Not implemented</li>
   *                   <li><b>3</b> - Forbidden</li>
   *                   <li><b>4</b> - Permission denied</li>
   *                   <li><b>5</b> - Validation fails</li>
   *                   <li><b>6</b> - Not found</li>
   *                   <li><b>7</b> - Internal server error</li>
   *               </ul>
   */
  code?: number;

  /**
   * Errors list
   */
  errors?: Array<string>;
}
