/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BillableData {
  team?: {

/**
 * Team name
 */
'name'?: string;

/**
 * Team slug
 */
'slug'?: string;
};
  user?: {

/**
 * User name
 */
'name'?: string;

/**
 * User email
 */
'email'?: string;
};
}
