/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type BrowserAnalyticsData = Array<{
'name'?: string;
'value'?: number;
'children'?: Array<{
'name'?: string;
'value'?: number;
}>;
}>;
