/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BulkRequestItem } from '../models/bulk-request-item';
export interface BulkRequest {

  /**
   * Default domain
   */
  domain?: string;

  /**
   * Array of items
   */
  items: Array<BulkRequestItem>;
}
