/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseResponse } from '../models/base-response';
import { BulkReportData } from '../models/bulk-report-data';
export type BulkReportResponse = {
'data'?: Array<BulkReportData>;
} & BaseResponse;
