/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BulkStatusData {

  /**
   * Date and time when bulk requst was created
   */
  created_at?: string;

  /**
   * Failed items count
   */
  failed?: number;

  /**
   * Bulk requst ID
   */
  id?: number;

  /**
   * Bulk requst status. Possible statuses:
   *            <ul>
   *                <li><b>0</b> - New</li>
   *                <li><b>1</b> - Processing</li>
   *                <li><b>2</b> - Processed</li>
   *            </ul>
   */
  status?: number;

  /**
   * Successfully processed items count
   */
  success?: number;

  /**
   * Total items count in bulk request
   */
  total?: number;

  /**
   * Date abd time when bulk requst was updated last time
   */
  updated_at?: string;
}
