/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserMetadata } from '../models/user-metadata';
export interface BulkReportData {

  /**
   * Requested alias
   */
  alias?: string;

  /**
   * Operation comment if operation failed
   */
  comment?: string;

  /**
   * Requested domain
   */
  domain?: string;

  /**
   * TinyURL expiration in ISO8601 format
   */
  expires_at?: string;
  metadata?: Array<UserMetadata>;

  /**
   * operation type
   */
  operation?: 'create' | 'update' | 'change' | 'delete' | 'archive' | 'unarchive';

  /**
   * Operation status
   */
  status?: 'success' | 'failed';

  /**
   * Created TinyURL
   */
  tinyurl?: string;

  /**
   * Shortened long URL
   */
  url?: string;
}
