/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseResponse } from '../models/base-response';
import { BulkStatusData } from '../models/bulk-status-data';
export type BulkStatusResponse = {
'data'?: BulkStatusData;
} & BaseResponse;
