/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CreateTinyUrlRequest } from '../models/create-tiny-url-request';
import { SourceTinyUrlRequest } from '../models/source-tiny-url-request';
import { UpdateTinyUrlRequest } from '../models/update-tiny-url-request';
import { UpdateUrlRequest } from '../models/update-url-request';
import { UserMetadata } from '../models/user-metadata';
export type BulkRequestItem = ({

/**
 * Requested operation type. Should be set to 'create'
 */
'operation'?: string;
} & {
'metadata'?: Array<UserMetadata>;
} & CreateTinyUrlRequest | {

/**
 * Requested operation type. Should be set to 'update'
 */
'operation'?: string;
} & {
'metadata'?: Array<UserMetadata>;
} & UpdateTinyUrlRequest | {

/**
 * Requested operation type. Should be set to 'change'
 */
'operation'?: string;
} & {
'metadata'?: Array<UserMetadata>;
} & UpdateUrlRequest | {

/**
 * Requested operation type. Should be set to 'delete'
 */
'operation'?: string;
} & {
'metadata'?: Array<UserMetadata>;
} & SourceTinyUrlRequest | {

/**
 * Requested operation type. Should be set to 'archive'
 */
'operation'?: string;
} & {
'metadata'?: Array<UserMetadata>;
} & SourceTinyUrlRequest | {

/**
 * Requested operation type. Should be set to 'unarchive'
 */
'operation'?: string;
} & {
'metadata'?: Array<UserMetadata>;
} & SourceTinyUrlRequest);
