/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTinyUrlRequest {

  /**
   * A short string of characters to use in the TinyURL. If ommitted, one will be randomly generated. When using a branded domain, this has a minimum length of 1 character
   */
  alias?: string;

  /**
   * The alias description
   */
  description?: string | null;

  /**
   * The domain you would like the TinyURL to use. Select from our free domain tinyurl.com or subscribe and use our <a href='/app/settings/branded-domains' target='_blank'>branded domains.</a>
   *                 <ul><li>tinyurl.com</li></ul>
   */
  domain?: string;

  /**
   * TinyURL expiration in ISO8601 format.<br>Set to null so TinyURL never expires
   */
  expires_at?: string | null;

  /**
   * Tags group and categorize TinyURLs together.
   */
  tags?: Array<string>;

  /**
   * The long URL that will be shortened
   */
  url: string;
}
