/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseResponse } from '../models/base-response';
import { GeneralAnalyticsData } from '../models/general-analytics-data';
export type GeneralAnalyticsResponse = {
'data'?: GeneralAnalyticsData;
} & BaseResponse;
