/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseResponse } from '../models/base-response';
export type GenericResponse = {

/**
 * Response data
 */
'data'?: ((Array<any> | {
} | string | number | number | boolean)) | null;
} & BaseResponse & {
};
