/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseResponse } from '../models/base-response';
import { HoursPopularityAnalyticsData } from '../models/hours-popularity-analytics-data';
export type HoursPopularityAnalyticsResponse = {
'data'?: HoursPopularityAnalyticsData;
} & BaseResponse;
