/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseResponse } from '../models/base-response';
import { LocationAnalyticsData } from '../models/location-analytics-data';
export type LocationAnalyticsResponse = {
'data'?: LocationAnalyticsData;
} & BaseResponse;
