/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LocationAnalyticsData {

  /**
   * Dataset items
   */
  dataset?: Array<{
'name'?: string;
'value'?: number;
}>;
  none?: number;
  total?: number;
}
