/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RawLogsAnalyticsData {
  browser?: {
'name'?: string | null;
'version'?: string | null;
};
  country?: string | null;
  datetime?: string;
  device?: string | null;
  ip?: string;
  is_bot?: boolean | null;
  language?: string | null;
  os?: {
'name'?: string | null;
'version'?: string | null;
};
  referer?: string | null;
  tags?: Array<string>;
  tiny_url?: string;
  url?: string;
}
