/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseResponse } from '../models/base-response';
import { RawLogsAnalyticsData } from '../models/raw-logs-analytics-data';
export type RawLogsAnalyticsResponse = {
'data'?: Array<RawLogsAnalyticsData>;
} & BaseResponse;
