/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SourceTinyUrlRequest {

  /**
   * Source alias
   */
  alias: string;

  /**
   * Source domain
   */
  domain: string;
}
