/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseResponse } from '../models/base-response';
import { TimelineAnalyticsData } from '../models/timeline-analytics-data';
export type TimelineAnalyticsResponse = {
'data'?: TimelineAnalyticsData;
} & BaseResponse;
