/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TimelineAnalyticsData {

  /**
   * Dataset items
   */
  dataset?: Array<{
'datetime'?: string;
'total'?: number;
'unique'?: number;
'human'?: number;
}>;

  /**
   * Used interval
   */
  interval?: 'minute' | 'hour' | 'day' | 'week' | 'month';

  /**
   * Used time zone
   */
  timezone?: string;
}
