/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TopSourcesAnalyticsData {

  /**
   * Dataset items
   */
  dataset?: Array<{
'source'?: string;
'hits'?: number;
}>;
  direct?: number;
  total?: number;
}
