/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TopLanguagesAnalyticsData {

  /**
   * Dataset items
   */
  dataset?: Array<{
'language'?: string;
'hits'?: number;
}>;
  none?: number;
  total?: number;
}
