/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseResponse } from '../models/base-response';
import { TopSourcesAnalyticsData } from '../models/top-sources-analytics-data';
export type TopSourcesAnalyticsResponse = {
'data'?: TopSourcesAnalyticsData;
} & BaseResponse;
