/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseResponse } from '../models/base-response';
import { TopLanguagesAnalyticsData } from '../models/top-languages-analytics-data';
export type TopLanguagesAnalyticsResponse = {
'data'?: TopLanguagesAnalyticsData;
} & BaseResponse;
