/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SourceTinyUrlRequest } from '../models/source-tiny-url-request';
export type UpdateAnalyticsSharingRequest = {
'public'?: boolean;
} & SourceTinyUrlRequest & {
};
