/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTinyUrlRequest {

  /**
   * The existing alias for this TinyURL
   */
  alias: string;

  /**
   * The existing domain for this TinyURL
   */
  domain: string;

  /**
   * The new alias you would like to switch to
   */
  new_alias?: string;

  /**
   * The new description
   */
  new_description?: string | null;

  /**
   * The new domain you would like to switch to
   */
  new_domain?: string;

  /**
   * TinyURL expiration in ISO8601 format.<br>Set to null so TinyURL never expires
   */
  new_expires_at?: string | null;

  /**
   * Turns on / off the collection of click analytics
   */
  new_stats?: boolean;

  /**
   * Tags you would like this TinyURL to have. Overwrites the existing tags.
   */
  new_tags?: Array<string>;
}
