/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseResponse } from '../models/base-response';
import { UrlData } from '../models/url-data';
export type UrlResponse = {
'data'?: UrlData;
} & BaseResponse;
