/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseResponse } from '../models/base-response';
import { UrlAliasHitsBillableData } from '../models/url-alias-hits-billable-data';
export type UrlAliasHitsBillableResponse = {
'data'?: UrlAliasHitsBillableData;
} & BaseResponse;
