/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseResponse } from '../models/base-response';
import { UrlAliasData } from '../models/url-alias-data';
export type UrlAliasResponse = {
'data'?: UrlAliasData;
} & BaseResponse;
