/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AliasData } from '../models/alias-data';
import { UrlData } from '../models/url-data';
export type UrlAliasData = AliasData & UrlData & {
};
