/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AliasData } from '../models/alias-data';
import { BillableData } from '../models/billable-data';
import { HitsData } from '../models/hits-data';
import { UrlData } from '../models/url-data';
export type UrlAliasHitsBillableData = AliasData & BillableData & HitsData & UrlData & {
};
