/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BaseResponse } from '../models/base-response';
import { WeekdaysPopularityAnalyticsData } from '../models/weekdays-popularity-analytics-data';
export type WeekdaysPopularityAnalyticsResponse = {
'data'?: WeekdaysPopularityAnalyticsData;
} & BaseResponse;
