/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WeekdaysPopularityAnalyticsData {

  /**
   * Dataset items
   */
  dataset?: Array<number>;
}
