/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Postcard {
  audio?: number;
  from: string;
  message: string;
  occasion: string;
  to: string;
}
