/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AliasResponse } from '../../models/alias-response';
import { SourceTinyUrlRequest } from '../../models/source-tiny-url-request';

export interface ArchiveTinyUrl$Params {
      body: SourceTinyUrlRequest
}

export function archiveTinyUrl(http: HttpClient, rootUrl: string, params: ArchiveTinyUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<AliasResponse>> {
  const rb = new RequestBuilder(rootUrl, archiveTinyUrl.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AliasResponse>;
    })
  );
}

archiveTinyUrl.PATH = '/archive';
