/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateUrlRequest } from '../../models/update-url-request';
import { UrlResponse } from '../../models/url-response';

export interface ChangeTinyUrl$Params {
      body: UpdateUrlRequest
}

export function changeTinyUrl(http: HttpClient, rootUrl: string, params: ChangeTinyUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<UrlResponse>> {
  const rb = new RequestBuilder(rootUrl, changeTinyUrl.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UrlResponse>;
    })
  );
}

changeTinyUrl.PATH = '/change';
