/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTinyUrlRequest } from '../../models/create-tiny-url-request';
import { UrlAliasResponse } from '../../models/url-alias-response';

export interface CreateTinyUrl$Params {
      body: CreateTinyUrlRequest
}

export function createTinyUrl(http: HttpClient, rootUrl: string, params: CreateTinyUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<UrlAliasResponse>> {
  const rb = new RequestBuilder(rootUrl, createTinyUrl.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UrlAliasResponse>;
    })
  );
}

createTinyUrl.PATH = '/create';
