/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UrlAliasResponse } from '../../models/url-alias-response';

export interface DeleteTinyUrl$Params {

/**
 * TinyURL domain
 */
  domain: string;

/**
 * TinyURL alias
 */
  alias: string;
}

export function deleteTinyUrl(http: HttpClient, rootUrl: string, params: DeleteTinyUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<UrlAliasResponse>> {
  const rb = new RequestBuilder(rootUrl, deleteTinyUrl.PATH, 'delete');
  if (params) {
    rb.path('domain', params.domain, {});
    rb.path('alias', params.alias, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UrlAliasResponse>;
    })
  );
}

deleteTinyUrl.PATH = '/alias/{domain}/{alias}';
