/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AliasesCountResponse } from '../../models/aliases-count-response';

export interface GetTinyUrlsCount$Params {

/**
 * aliases list type
 */
  type: 'available' | 'archived';

/**
 * Datetime, indicating that only TinyURLs created after the datetime will be selected.
 */
  from?: string;

/**
 * Datetime, indicating that only TinyURLs created before the datetime will be selected.
 */
  to?: string;

/**
 * search for tag or alias
 */
  search?: string;
}

export function getTinyUrlsCount(http: HttpClient, rootUrl: string, params: GetTinyUrlsCount$Params, context?: HttpContext): Observable<StrictHttpResponse<AliasesCountResponse>> {
  const rb = new RequestBuilder(rootUrl, getTinyUrlsCount.PATH, 'get');
  if (params) {
    rb.path('type', params.type, {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
    rb.query('search', params.search, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AliasesCountResponse>;
    })
  );
}

getTinyUrlsCount.PATH = '/urls/{type}/count';
