/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LocationAnalyticsResponse } from '../../models/location-analytics-response';

export interface LocationAnalytics$Params {

/**
 * Datetime, indicating start datetime of analytics report.
 */
  from: string;

/**
 * Datetime, indicating end datetime of analytics report. Will default to current time.
 */
  to?: string;

/**
 * Country Alpha-2 ISO 3166-1 code. Leave blank for countries
 */
  region: string;

/**
 * TinyURL to get analytics for
 */
  alias?: string;

/**
 * Tag to get analytics for
 */
  tag?: string;
}

export function locationAnalytics(http: HttpClient, rootUrl: string, params: LocationAnalytics$Params, context?: HttpContext): Observable<StrictHttpResponse<LocationAnalyticsResponse>> {
  const rb = new RequestBuilder(rootUrl, locationAnalytics.PATH, 'get');
  if (params) {
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
    rb.path('region', params.region, {});
    rb.query('alias', params.alias, {});
    rb.query('tag', params.tag, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LocationAnalyticsResponse>;
    })
  );
}

locationAnalytics.PATH = '/analytics/location/{region}';
