/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TopSourcesAnalyticsResponse } from '../../models/top-sources-analytics-response';

export interface TopSourcesAnalytics$Params {

/**
 * Datetime, indicating start datetime of analytics report.
 */
  from: string;

/**
 * Datetime, indicating end datetime of analytics report. Will default to current time.
 */
  to?: string;

/**
 * TinyURL to get analytics for
 */
  alias?: string;

/**
 * Tag to get analytics for
 */
  tag?: string;
}

export function topSourcesAnalytics(http: HttpClient, rootUrl: string, params: TopSourcesAnalytics$Params, context?: HttpContext): Observable<StrictHttpResponse<TopSourcesAnalyticsResponse>> {
  const rb = new RequestBuilder(rootUrl, topSourcesAnalytics.PATH, 'get');
  if (params) {
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
    rb.query('alias', params.alias, {});
    rb.query('tag', params.tag, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TopSourcesAnalyticsResponse>;
    })
  );
}

topSourcesAnalytics.PATH = '/analytics/sources/top';
